In [7]:
import numpy as np
import sympy as sym

Уровень 0:
Представим фильмы в виде бинарных векторов (numpy array) используя следующие признаки:

[Комедия, Боевик, Исторический, Бред Питт, Бенедикт Камбербэтч, Квентин Тарантино]

Игра в имитацию

Ярость

12 лет рабства

Однажды в Голливуде

film_1 = np.array([0,0,0,0,1,0])      # Игра в имитацию

film_2 = np.array([0,1,0,1,0,0])      # Ярость

film_3 = np.array([0,0,1,1,1,0])      # 12 лет рабства

film_4 = np.array([1,0,0,1,0,1])      # Однажды в Голливуде

In [2]:
film_1 = np.array([0,0,0,0,1,0])
film_2 = np.array([0,1,0,1,0,0])
film_3 = np.array([0,0,1,1,1,0])  
film_4 = np.array([1,0,0,1,0,1]) 

In [3]:
film_1

array([0, 0, 0, 0, 1, 0])

## Задание 1
* Найти угол между векторами-фильмами "Ярость" и "12 лет рабства". Результатом будет являться косинусная мера, которую можно использовать для определения похожести векторов.

In [4]:
dot_pr = film_2.dot(film_3)
norms = np.linalg.norm(film_2) * np.linalg.norm(film_3)
np.rad2deg(np.arccos(dot_pr / norms))

65.90515744788931

## Задание 2 
* Вычислить с помощью Python значение первой производной для функции 3*x*(x**2+x)**3 в точке x=1

In [8]:
x = sym.Symbol('x')

In [9]:
res = sym.diff(3*x*(x**2+x)**3)

In [10]:
res.subs(x,1)

132

## Задание 3
* Объединить векторы фильмов в матрицу, где каждый вектор является строкой матрицы. Умножьте вектор [1,2,3,4] на полученную матрицу

In [11]:
vector = np.array([1,2,3,4])

In [13]:
matrix = np.array([film_1, film_2, film_3, film_4])

In [14]:
matrix

array([[0, 0, 0, 0, 1, 0],
       [0, 1, 0, 1, 0, 0],
       [0, 0, 1, 1, 1, 0],
       [1, 0, 0, 1, 0, 1]])

In [15]:
vector @ matrix

array([4, 2, 3, 9, 4, 4])